#!/bin/sh

echo "Merge realizado com sucesso!"

make lint
if [ $? -ne 0 ]
then
  echo "#####################################################"
  echo "##                                                 ##"
  echo "##          Aborted - make lint failed             ##"
  echo "##                                                 ##"
  echo "#####################################################"
	exit 1
fi

make test
if [ $? -ne 0 ]
then
    echo "#####################################################"
    echo "##                                                 ##"
    echo "##          Aborted - make test failed             ##"
    echo "##                                                 ##"
    echo "#####################################################"
	exit 1
fi

echo "Todas as ações post-merge foram executadas com sucesso!"